services:
  minio:
    image: minio/minio:latest
    container_name: bda-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    networks:
      - bda-network
    command: server /data --console-address ":9001"

  spark-master:
    image: bitnamilegacy/spark:3.5.1
    container_name: bda-spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - bda-network

  spark-worker:
    image: bitnamilegacy/spark:3.5.1
    container_name: bda-spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - bda-network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: bda-jupyter
    ports:
      - "8888:8888"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - bda-network

networks:
  bda-network:
    driver: bridge

volumes:
  minio_data: