datasets:
  - id: "employee_train"
    name: "Training Data"
    source_path: "data/train.csv"
    target_bucket: "datalake"
    target_object_name: "bronze/train/train.csv"
  - id: "employee_test"
    name: "Testing Data"
    source_path: "data/test.csv"
    target_bucket: "datalake"
    target_object_name: "bronze/test/test.csv"