datasets:
  - name: "Training Data"
    source_path: "train.csv"  # Sebelumnya "data/train.csv"
    target_bucket: "datalake"
    target_object_name: "bronze/train/train.csv"
  - name: "Testing Data"
    source_path: "test.csv"   # Sebelumnya "data/test.csv"
    target_bucket: "datalake"
    target_object_name: "bronze/test/test.csv"